force-app/main/default/objects/Person__x/Person__x.object-meta.xml
<CustomObject>
    <description>Person</description>
    <externalDataSource>xDM</externalDataSource>
    <externalName>Person</externalName>
    <label>Person</label>
    <pluralLabel>Person</pluralLabel>
</CustomObject>

force-app/main/default/objects/Person__x/fields/EnrichedPrimaryEmail__c.field-meta.xml
<CustomField>
    <fullName>EnrichedPrimaryEmail__c</fullName>
    <description>EnrichedPrimaryEmail</description>
    <externalDeveloperName>EnrichedPrimaryEmail</externalDeveloperName>
    <label>EnrichedPrimaryEmail</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person__x/fields/EnrichedPrimaryPhone__c.field-meta.xml
<CustomField>
    <fullName>EnrichedPrimaryPhone__c</fullName>
    <description>EnrichedPrimaryPhone</description>
    <externalDeveloperName>EnrichedPrimaryPhone</externalDeveloperName>
    <label>EnrichedPrimaryPhone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person__x/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>FirstName</description>
    <externalDeveloperName>FirstName</externalDeveloperName>
    <label>FirstName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person__x/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>LastName</description>
    <externalDeveloperName>LastName</externalDeveloperName>
    <label>LastName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person__x/fields/MiddleName__c.field-meta.xml
<CustomField>
    <fullName>MiddleName__c</fullName>
    <description>MiddleName</description>
    <externalDeveloperName>MiddleName</externalDeveloperName>
    <label>MiddleName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person__x/fields/MPA_FormattedAddress__c.field-meta.xml
<CustomField>
    <fullName>MPA_FormattedAddress__c</fullName>
    <description>MPA_FormattedAddress</description>
    <externalDeveloperName>MPA_FormattedAddress</externalDeveloperName>
    <label>MPA_FormattedAddress</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ContactCreateController.cls
public with sharing class ContactCreateController {
    public Person__x getPerson() {
        return [ SELECT FirstName__c, LastName__c, MiddleName__c, EnrichedPrimaryEmail__c, EnrichedPrimaryPhone__c, MPA_FormattedAddress__c
                 FROM Person__x 
                 WHERE ExternalId = :Apexpages.currentPage().getParameters().get('id')][0];
    }

    public Pagereference submit() {
        return null;
    }

    public Pagereference cancel() {
        return null;
    }
}